server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://3.141.20.73:30001/contiq
    username: root
    password: Bootcamp@116!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  flyway:
    baseline-on-migrate: true
    locations: filesystem:db/migration
    outOfOrder: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/